### ISSUE TITLE
[onyxia] Ingress has nginx-ingress-controler specifics

### ISSUE THREAD

**Issue by sathieu** [InseeFrLab/helm-charts#23]
From [ingress.yaml](https://github.com/InseeFrLab/helm-charts/blob/f1f36675ecc7efb07d9ab5a20e70e3303033751c/charts/onyxia/templates/ingress.yaml):

```yaml
# ...
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  # ...
  annotations:
    # ...
    nginx.ingress.kubernetes.io/rewrite-target: /$1  # <===== here

spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api/(.*)  # <===== here
            pathType: Prefix  # <===== here, it's actually ImplementationSpecific
            backend:
              service:
                name: {{ $fullNameApi }}
                port: 
                  number: {{ $svcPortApi }}
          - path: /(.*)  # <===== here
            pathType: Prefix  # <===== here, it's actually ImplementationSpecific
            backend: 
              service:
                name: {{ $fullNameUi }}
                port: 
                  number: {{ $svcPortUi }}
# ...
```

To solve this, the API should handle requests to `/api` (and not `/`).

Alternatively, another host name for the API can be used.

Proposed roadmap:

- [x]  https://github.com/InseeFrLab/onyxia-api/pull/109
- [ ] https://github.com/InseeFrLab/helm-charts/pull/25
