### ISSUE TITLE
Onyxia service account

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/helm-charts#31]
To let onyxia run with less security privilege in the cluster, we should try to change service account part of the chart to take profit ot this PR on onyxia-api https://github.com/InseeFrLab/onyxia-api/issues/74

**Comment by alexisdondon** [comment]
I will make that suggest this change 
```
{{- if .Values.serviceAccount.create -}}
{{- if .Values.serviceAccount.clusterAdmin -}}
apiVersion: [rbac.authorization.k8s.io/v1](http://rbac.authorization.k8s.io/v1)
kind: ClusterRoleBinding
metadata:
  name: {{ include "onyxia.fullname" . }}
  labels:
    {{- include "onyxia.api.labels" . | nindent 4 }}
roleRef:
  apiGroup: [rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "onyxia.api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.serviceAccount.clusterMinPrivilege -}}
---
apiVersion: [rbac.authorization.k8s.io/v1](http://rbac.authorization.k8s.io/v1)
kind: ClusterRole
metadata:
  name: clusterMinPrivilegeRole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create"]
- apiGroups: ["[rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)"]
  resources: ["rolebindings"]
  verbs: ["create"]
- apiGroups: ["[rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)"]
  resources: ["clusterroles"]
  verbs: ["bind"]
  resourceNames: ["admin","edit","view"]
---
apiVersion: [rbac.authorization.k8s.io/v1](http://rbac.authorization.k8s.io/v1)
kind: ClusterRoleBinding
metadata:
  name: {{ include "onyxia.fullname" . }}
  labels:
    {{- include "onyxia.api.labels" . | nindent 4 }}
roleRef:
  apiGroup: [rbac.authorization.k8s.io](http://rbac.authorization.k8s.io/)
  kind: ClusterRole
  name: clusterMinPrivilegeRole
subjects:
- kind: ServiceAccount
  name: {{ include "onyxia.api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
```
