### ISSUE TITLE
Onyxia chart values validation error when `extraVolumes` is configured

### ISSUE THREAD

**Issue by sergkudinov** [InseeFrLab/helm-charts#38]
Validation error when providing `extraVolumes` to Onyxia chart values.

Example values.yaml:

```
...
ui:
...
  extraVolumes:
  - name: my-vol
    secret:
      secretName: my-secret
api:
...
  extraVolumes:
  - name: my-vol
    secret:
      secretName: my-secret
```

Error:

```
Error: error validating "": error validating data: ValidationError(Deployment.spec.template): unknown field "volumes" in io.k8s.api.core.v1.PodTemplateSpec
```
