### ISSUE TITLE
Helm chart of S3 operator cannot disable SSL

### ISSUE THREAD

**Issue by FrankFoerster24** [InseeFrLab/helm-charts#57]
Hi,

I see no way to disable SSL by passing `--useSsl=false` to the operator.  Can we add this capability?

Kind regards,
 Frank.

**Comment by FrankFoerster24** [comment]
PR #56 would make this possible.

**Comment by phlg** [comment]
Closing the issue as the related PR has been merged. Didn't try the added feature first-hand, but I guess the way to use it (relative to SSL disabling) could look something like this (in values file) : 

```yaml
controllerManager:
  manager:
    # other options
    extraArgs: 
      - --useSsl=false
```
