### ISSUE TITLE
add support for different secret key names

### ISSUE THREAD

**Issue by dberardo-com** [InseeFrLab/helm-charts#64]
the value of "S3_ACCESS_KEY" should also be adjustable from the values file. same goes for the secret key
```
          valueFrom:
            secretKeyRef:
              name: {{ .Values.s3.existingSecret }}
              key: S3_ACCESS_KEY
```
