### ISSUE TITLE
s3-operator flag provided but not defined: -s3-endpoint-url

### ISSUE THREAD

**Issue by frostyfab** [InseeFrLab/helm-charts#84]
Using the helm chart `inseefrlab\s3-operator` (v0.5) with value:

```
s3:
  endpointUrl: minio.platform:9000
```

results in error on `s3-operator` pod (image: `inseefrlab/s3-operator:latest`):

```
flag provided but not defined: -s3-endpoint-url
```

Probable cause is that the parameter has been removed/renamed and since the image in the chart is not versioned it fails with newer manager.

**Comment by frostyfab** [comment]
Updating to chart version 0.6 (latest) stable shows same issues.

**Comment by frostyfab** [comment]
Workaround supply image tag in chart values:

```
 controllerManager:
      manager:
        image: # workaround for: https://github.com/InseeFrLab/helm-charts/issues/84
          tag: v0.11.0 
        extraArgs:
          - --region=polar
          - --useSsl=false
    s3:
      endpointUrl: minio.platform:9000
```

Tag `v0.11.0` tested with chart version 0.6. The v0.12x images seem to not support `-s3-endpoint-url` flag anymore. The root issue is that release candidate images are getting supplied to stable chart versions (`latest` instead of tag).
